name: Node-js CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Set up environment file
        run: echo "${{ secrets.STAGE_ENV }}" > .env
      - run: pnpm run bundle
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: bundle/

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          rm: true
          source: "bundle/*"
          strip_components: 1
          target: ${{ secrets.DEPLOY_SERVER_PROJECT_PATH }}/dist
      - name: Install dependencies on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_SERVER_PROJECT_PATH }}/dist
            pnpm install --production
      - name: Restart Node.js Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_SERVER_PROJECT_PATH }}/dist
            pm2 stop index.js
            pm2 delete index.js
            pm2 start index.js
